"""
Records keyboard and mouse input and turns it into two independent lists of
Blocks - one per track (see model.Script). Each track keeps its own "time
since the last event on this track" gap accounting, entirely independent of
the other - a keyboard tap no longer interrupts an in-progress mouse
gesture, and vice versa. Since both counters are driven by the same
wall-clock and both start recording at the same instant, the two tracks
stay correctly synchronized when played back together without needing any
separate per-block timestamp.

Design:
- Keyboard: every press/release becomes its own block - no automatic
  grouping of "simultaneous" key holds, the user merges related blocks
  manually afterwards with the editor's Merge tool.
- Mouse: moves and button down/up events accumulate into a single
  "mouse_path" block as one continuous sequence of typed points, so a
  gesture-with-clicks doesn't fragment into a move block, then a click
  block, then another move block. A new block only starts after a
  significant pause in mouse activity (MOUSE_BLOCK_SPLIT_GAP), purely to
  keep the block list organized into meaningful chunks.
- Mouse buttons are recorded as separate down/up events with the real time
  between them (not a fixed-duration "click"), and mouse positions are
  recorded as absolute coordinates rather than relative deltas - Windows
  applies pointer-acceleration curves to relative SendInput moves, which
  made played-back movement drift from where it was recorded.
"""

import ctypes
import time

from PySide6.QtCore import QObject, Signal

from ..core.hooks import KeyboardHook, MouseHook
from ..core.constants import SCAN_TO_CODE, SCAN_TO_CODE_EXT, IS_WINDOWS
from ..core.input import get_mouse_position
from ..model import Block, Step, MousePathPoint

WM_KEYDOWN = 0x0100
WM_KEYUP = 0x0101
WM_SYSKEYDOWN = 0x0104
WM_SYSKEYUP = 0x0105

WM_MOUSEMOVE = 0x0200
WM_LBUTTONDOWN = 0x0201
WM_LBUTTONUP = 0x0202
WM_RBUTTONDOWN = 0x0204
WM_RBUTTONUP = 0x0205

VK_CONTROL = 0x11
VK_SHIFT = 0x10
VK_MENU = 0x12  # Alt

# Modifier keys are never recorded into a macro (either side) - only ever used
# to disambiguate a start/stop-recording hotkey combo, never as macro content.
MODIFIER_CODES = {"lctrl", "rctrl", "lshift", "rshift", "lalt", "ralt"}

# LLKHF_INJECTED | LLKHF_LOWER_IL_INJECTED - set when a keyboard event was
# generated by SendInput (e.g. another KeyMimic thread's own running macro)
# rather than typed on real hardware. Recordings must only ever contain real
# physical input, so these are always skipped.
LLKHF_INJECTED_MASK = 0x10 | 0x20
# LLMHF_INJECTED | LLMHF_LOWER_IL_INJECTED - the mouse equivalent.
LLMHF_INJECTED_MASK = 0x01 | 0x02

MOUSE_SAMPLE_INTERVAL = 0.02   # seconds between recorded mouse-move samples
MOUSE_MOVE_THRESHOLD = 5       # minimum pixels moved to record a new sample
MIN_RECORDED_GAP = 0.01        # ignore gaps smaller than this (event-loop noise)
MOUSE_BLOCK_SPLIT_GAP = 1.0    # seconds of mouse inactivity that starts a new Mouse Path block


class RecorderSignals(QObject):
    """Emitted when a configured start/stop-recording hotkey is pressed mid-recording."""

    control_hotkey = Signal(str)  # "start_record" or "stop_record"


class Recorder:
    """Records keyboard (and optionally mouse) input using composition over the hooks."""

    def __init__(self, record_mouse: bool = False):
        self.record_mouse = record_mouse
        self.recording = False

        self.keyboard_events = []  # list of (name, args) - "press"/"release"/"sleep"
        self.mouse_events = []     # list of (name, args) - "move"/"*_down"/"*_up"/"sleep"
        self._last_keyboard_time = None
        self._last_mouse_event_time = None

        self.keyboard_hook = None
        self.mouse_hook = None

        self._last_mouse_pos = None
        self._last_mouse_sample_time = None
        self.start_mouse_pos = None

        self.signals = RecorderSignals()
        # (code, ctrl, shift, alt) -> action name ("start_record" / "stop_record").
        # These exact combos are never recorded as macro steps, and pressing the
        # "stop_record" one fires `signals.control_hotkey` instead of being logged.
        self._control_hotkeys = {}

    def set_control_hotkeys(self, bindings: dict):
        """
        Configure which exact key combos are reserved for recording control.

        Args:
            bindings: {"start_record": {"key":..,"ctrl":..,"shift":..,"alt":..}, "stop_record": {...}}
        """
        self._control_hotkeys = {}
        for action, binding in bindings.items():
            if not binding:
                continue
            combo = (
                binding.get("key"),
                binding.get("ctrl", False),
                binding.get("shift", False),
                binding.get("alt", False),
            )
            self._control_hotkeys[combo] = action

    def start(self, record_mouse=None):
        if not IS_WINDOWS:
            return
        if record_mouse is not None:
            self.record_mouse = record_mouse

        self.recording = True
        self.keyboard_events = []
        self.mouse_events = []
        self._last_keyboard_time = time.time()
        self._last_mouse_event_time = time.time()
        self._last_mouse_pos = None
        self._last_mouse_sample_time = None
        self.start_mouse_pos = get_mouse_position()

        self.keyboard_hook = KeyboardHook(self._on_keyboard_event)
        self.keyboard_hook.start()

        if self.record_mouse:
            self.mouse_hook = MouseHook(self._on_mouse_event)
            self.mouse_hook.start()

    def stop(self):
        """Stop recording and return (keyboard_blocks, mouse_blocks)."""
        self.recording = False

        if self.keyboard_hook:
            self.keyboard_hook.stop()
            self.keyboard_hook = None
        if self.mouse_hook:
            self.mouse_hook.stop()
            self.mouse_hook = None

        return self._build_keyboard_blocks(), self._build_mouse_blocks()

    # -- hook callbacks -----------------------------------------------------

    def _on_keyboard_event(self, nCode, wParam, kb_struct):
        if not self.recording:
            return
        if wParam not in (WM_KEYDOWN, WM_KEYUP, WM_SYSKEYDOWN, WM_SYSKEYUP):
            return
        if kb_struct.flags & LLKHF_INJECTED_MASK:
            return  # synthetic input (e.g. another running macro), not the real user

        extended = (kb_struct.flags & 0x1) != 0
        code = (SCAN_TO_CODE_EXT if extended else SCAN_TO_CODE).get(kb_struct.scanCode)
        if not code:
            return

        is_down = wParam in (WM_KEYDOWN, WM_SYSKEYDOWN)

        if code in MODIFIER_CODES:
            # Never recorded as macro content - see module docstring / SPEC 10.4.
            return

        if self._control_hotkeys:
            ctrl = (ctypes.windll.user32.GetKeyState(VK_CONTROL) & 0x8000) != 0
            shift = (ctypes.windll.user32.GetKeyState(VK_SHIFT) & 0x8000) != 0
            alt = (ctypes.windll.user32.GetKeyState(VK_MENU) & 0x8000) != 0
            action = self._control_hotkeys.get((code, ctrl, shift, alt))
            if action:
                # Reserved for recording control: never let it land in the
                # macro, and fire the action once (on key-down) instead.
                if is_down:
                    self.signals.control_hotkey.emit(action)
                return

        now = time.time()
        if self._last_keyboard_time is not None:
            gap = now - self._last_keyboard_time
            if gap > MIN_RECORDED_GAP:
                self.keyboard_events.append(("sleep", [round(gap, 3)]))
        self._last_keyboard_time = now

        self.keyboard_events.append(("press" if is_down else "release", [code]))

    def _record_mouse_gap(self):
        now = time.time()
        if self._last_mouse_event_time is not None:
            gap = now - self._last_mouse_event_time
            if gap > MIN_RECORDED_GAP:
                self.mouse_events.append(("sleep", [round(gap, 3)]))
        self._last_mouse_event_time = now

    def _on_mouse_event(self, nCode, wParam, mouse_struct):
        if not self.recording:
            return
        if mouse_struct.flags & LLMHF_INJECTED_MASK:
            return  # synthetic input (e.g. another running macro), not the real user
        current_pos = (mouse_struct.pt.x, mouse_struct.pt.y)

        if wParam == WM_LBUTTONDOWN:
            self._record_mouse_gap()
            self.mouse_events.append(("left_down", []))
            return
        if wParam == WM_LBUTTONUP:
            self._record_mouse_gap()
            self.mouse_events.append(("left_up", []))
            return
        if wParam == WM_RBUTTONDOWN:
            self._record_mouse_gap()
            self.mouse_events.append(("right_down", []))
            return
        if wParam == WM_RBUTTONUP:
            self._record_mouse_gap()
            self.mouse_events.append(("right_up", []))
            return

        if wParam == WM_MOUSEMOVE:
            now = time.time()
            if (self._last_mouse_sample_time is not None and
                    now - self._last_mouse_sample_time < MOUSE_SAMPLE_INTERVAL):
                return

            if self._last_mouse_pos is not None:
                dx = current_pos[0] - self._last_mouse_pos[0]
                dy = current_pos[1] - self._last_mouse_pos[1]
                if (dx * dx + dy * dy) ** 0.5 >= MOUSE_MOVE_THRESHOLD:
                    self._record_mouse_gap()
                    self.mouse_events.append(("move", [current_pos[0], current_pos[1]]))
                    self._last_mouse_pos = current_pos
                    self._last_mouse_sample_time = now
            else:
                self._last_mouse_pos = current_pos
                self._last_mouse_sample_time = now

    # -- post-processing: raw events -> Blocks -------------------------------

    def _dedupe_key_repeat(self, events):
        """Drop OS auto-repeat WM_KEYDOWN spam for keys that are already held."""
        held = set()
        result = []
        for name, args in events:
            if name == "press":
                code = args[0]
                if code in held:
                    continue
                held.add(code)
            elif name == "release":
                held.discard(args[0])
            result.append((name, args))
        return result

    def _build_keyboard_blocks(self):
        blocks = []
        events = self._dedupe_key_repeat(self.keyboard_events)

        pending_delay = 0.0
        for name, args in events:
            if name == "sleep":
                pending_delay += args[0]
                continue
            steps = []
            if pending_delay > MIN_RECORDED_GAP:
                steps.append(Step(type="sleep", duration=round(pending_delay, 2)))
            pending_delay = 0.0
            steps.append(Step(type=name, key=args[0]))
            blocks.append(Block.new_block(steps))

        return blocks

    def _build_mouse_blocks(self):
        blocks = []

        if self.record_mouse and self.start_mouse_pos:
            sx, sy = self.start_mouse_pos
            start_block = Block.new_mouse_path([MousePathPoint(kind="move", x=sx, y=sy)])
            start_block.label = "Return to starting position"
            blocks.append(start_block)

        pending_delay = 0.0
        path_points = None  # list[MousePathPoint] while a path run is open, else None

        def flush_path():
            nonlocal path_points
            if path_points:
                blocks.append(Block.new_mouse_path(path_points))
            path_points = None

        for name, args in self.mouse_events:
            if name == "sleep":
                pending_delay += args[0]
                if pending_delay >= MOUSE_BLOCK_SPLIT_GAP:
                    flush_path()
                continue

            if path_points is None:
                path_points = []

            if name == "move":
                x, y = args
                path_points.append(MousePathPoint(kind="move", x=x, y=y, dt=round(pending_delay, 3)))
            else:
                path_points.append(MousePathPoint(kind=name, dt=round(pending_delay, 3)))
            pending_delay = 0.0

        flush_path()
        return blocks
