"""
Records keyboard and mouse input and turns it into two independent lists of
Blocks - one per track (see model.Script). Each track keeps its own "time
since the last event on this track" gap accounting, entirely independent of
the other - a keyboard tap no longer interrupts an in-progress mouse
gesture, and vice versa. Since both counters are driven by the same
wall-clock and both start recording at the same instant, the two tracks
stay correctly synchronized when played back together without needing any
separate per-block timestamp.

Design:
- Keyboard: press/release events accumulate into a single block as one
  continuous sequence of steps, the same way the mouse side already worked -
  a new block only starts after a real pause (KEYBOARD_BLOCK_SPLIT_GAP).
  Recording one block per key event used to be the default, but that turns
  a few minutes of typing into thousands of top-level blocks - each
  needing its own real Qt widget with no virtualization in the editor,
  which made long recordings take minutes to render or even reopen.
- Mouse: moves and button down/up events accumulate into a single
  "mouse_path" block as one continuous sequence of typed points, so a
  gesture-with-clicks doesn't fragment into a move block, then a click
  block, then another move block. A new block only starts after a
  significant pause in mouse activity (MOUSE_BLOCK_SPLIT_GAP), purely to
  keep the block list organized into meaningful chunks.
- Mouse buttons are recorded as separate down/up events with the real time
  between them (not a fixed-duration "click"), and mouse positions are
  recorded as absolute coordinates rather than relative deltas - Windows
  applies pointer-acceleration curves to relative SendInput moves, which
  made played-back movement drift from where it was recorded.
- Movement recorded while a mouse button is held *and the OS cursor is
  hidden* is the one exception - it's captured as relative deltas
  ("move_rel" points) instead of absolute positions. Many games switch to
  reading raw relative mouse input for camera look/aim while a button is
  held, hiding (and often confining) the OS cursor while doing so - its
  absolute position during that time isn't meaningful, so recording/
  replaying a delta (matching what the game itself reads) is what actually
  works there. An ordinary held-button drag where the cursor stays visible
  (e.g. dragging an item in an inventory UI) keeps using absolute
  coordinates as normal - only "held + cursor hidden" switches to deltas.
"""

import ctypes
import time

from PySide6.QtCore import QObject, Signal

from ..core.hooks import KeyboardHook, MouseHook
from ..core.constants import SCAN_TO_CODE, SCAN_TO_CODE_EXT, IS_WINDOWS
from ..core.input import get_mouse_position, is_cursor_visible
from ..model import Block, Step, MousePathPoint

WM_KEYDOWN = 0x0100
WM_KEYUP = 0x0101
WM_SYSKEYDOWN = 0x0104
WM_SYSKEYUP = 0x0105

WM_MOUSEMOVE = 0x0200
WM_LBUTTONDOWN = 0x0201
WM_LBUTTONUP = 0x0202
WM_RBUTTONDOWN = 0x0204
WM_RBUTTONUP = 0x0205

VK_CONTROL = 0x11
VK_SHIFT = 0x10
VK_MENU = 0x12  # Alt

# Modifier keys are never recorded into a macro (either side) - only ever used
# to disambiguate a start/stop-recording hotkey combo, never as macro content.
MODIFIER_CODES = {"lctrl", "rctrl", "lshift", "rshift", "lalt", "ralt"}

# LLKHF_INJECTED | LLKHF_LOWER_IL_INJECTED - set when a keyboard event was
# generated by SendInput (e.g. another KeyMimic thread's own running macro)
# rather than typed on real hardware. Recordings must only ever contain real
# physical input, so these are always skipped.
LLKHF_INJECTED_MASK = 0x10 | 0x20
# LLMHF_INJECTED | LLMHF_LOWER_IL_INJECTED - the mouse equivalent.
LLMHF_INJECTED_MASK = 0x01 | 0x02

MOUSE_SAMPLE_INTERVAL = 0.02   # seconds between recorded mouse-move samples
MOUSE_MOVE_THRESHOLD = 5       # minimum pixels moved to record a new sample
MIN_RECORDED_GAP = 0.01        # ignore gaps smaller than this (event-loop noise)
MOUSE_BLOCK_SPLIT_GAP = 3.0    # seconds of mouse inactivity that starts a new Mouse Path block
KEYBOARD_BLOCK_SPLIT_GAP = 3.0  # seconds of keyboard inactivity that starts a new block


class RecorderSignals(QObject):
    """Emitted when a configured start/stop-recording hotkey is pressed mid-recording."""

    control_hotkey = Signal(str)  # "start_record" or "stop_record"


class Recorder:
    """Records keyboard (and optionally mouse) input using composition over the hooks."""

    def __init__(self, record_mouse: bool = False):
        self.record_mouse = record_mouse
        self.recording = False

        self.keyboard_events = []  # list of (name, args) - "press"/"release"/"sleep"
        self.mouse_events = []     # list of (name, args) - "move"/"*_down"/"*_up"/"sleep"
        self._last_keyboard_time = None
        self._last_mouse_event_time = None

        self.keyboard_hook = None
        self.mouse_hook = None

        self._last_mouse_pos = None
        self._last_mouse_sample_time = None
        self.start_mouse_pos = None
        # While a button is held, movement is recorded as relative deltas
        # instead of absolute positions - see MousePathPoint's docstring.
        self._left_held = False
        self._right_held = False

        self.signals = RecorderSignals()
        # (code, ctrl, shift, alt) -> action name ("start_record" / "stop_record").
        # These exact combos are never recorded as macro steps, and pressing the
        # "stop_record" one fires `signals.control_hotkey` instead of being logged.
        self._control_hotkeys = {}

    def set_control_hotkeys(self, bindings: dict):
        """
        Configure which exact key combos are reserved for recording control.

        Args:
            bindings: {"start_record": {"key":..,"ctrl":..,"shift":..,"alt":..}, "stop_record": {...}}
        """
        self._control_hotkeys = {}
        for action, binding in bindings.items():
            if not binding:
                continue
            combo = (
                binding.get("key"),
                binding.get("ctrl", False),
                binding.get("shift", False),
                binding.get("alt", False),
            )
            self._control_hotkeys[combo] = action

    def start(self, record_mouse=None):
        if not IS_WINDOWS:
            return
        if record_mouse is not None:
            self.record_mouse = record_mouse

        self.recording = True
        self.keyboard_events = []
        self.mouse_events = []
        self._last_keyboard_time = time.time()
        self._last_mouse_event_time = time.time()
        self._last_mouse_pos = None
        self._last_mouse_sample_time = None
        self.start_mouse_pos = get_mouse_position()
        self._left_held = False
        self._right_held = False

        self.keyboard_hook = KeyboardHook(self._on_keyboard_event)
        self.keyboard_hook.start()

        if self.record_mouse:
            self.mouse_hook = MouseHook(self._on_mouse_event)
            self.mouse_hook.start()

    def stop(self):
        """Stop recording and return (keyboard_blocks, mouse_blocks)."""
        self.recording = False

        if self.keyboard_hook:
            self.keyboard_hook.stop()
            self.keyboard_hook = None
        if self.mouse_hook:
            self.mouse_hook.stop()
            self.mouse_hook = None

        return self._build_keyboard_blocks(), self._build_mouse_blocks()

    def preview_blocks(self):
        """
        Non-destructive snapshot of the blocks recorded so far, without
        stopping the recording - used by the GUI to show a live preview of
        the in-progress recording. Safe to call from the GUI thread while
        the hooks (on their own dedicated thread) keep appending to
        self.keyboard_events/self.mouse_events: the hook thread only ever
        appends, this only ever reads, and CPython list iteration handles a
        list growing concurrently without corruption - worst case this
        preview is a fraction of a second stale, which is fine for a live
        view.
        """
        return self._build_keyboard_blocks(), self._build_mouse_blocks()

    # -- hook callbacks -----------------------------------------------------

    def _on_keyboard_event(self, nCode, wParam, kb_struct):
        if not self.recording:
            return
        if wParam not in (WM_KEYDOWN, WM_KEYUP, WM_SYSKEYDOWN, WM_SYSKEYUP):
            return
        if kb_struct.flags & LLKHF_INJECTED_MASK:
            return  # synthetic input (e.g. another running macro), not the real user

        extended = (kb_struct.flags & 0x1) != 0
        code = (SCAN_TO_CODE_EXT if extended else SCAN_TO_CODE).get(kb_struct.scanCode)
        if not code:
            return

        is_down = wParam in (WM_KEYDOWN, WM_SYSKEYDOWN)

        if code in MODIFIER_CODES:
            # Never recorded as macro content - see module docstring / SPEC 10.4.
            return

        if self._control_hotkeys:
            ctrl = (ctypes.windll.user32.GetKeyState(VK_CONTROL) & 0x8000) != 0
            shift = (ctypes.windll.user32.GetKeyState(VK_SHIFT) & 0x8000) != 0
            alt = (ctypes.windll.user32.GetKeyState(VK_MENU) & 0x8000) != 0
            action = self._control_hotkeys.get((code, ctrl, shift, alt))
            if action:
                # Reserved for recording control: never let it land in the
                # macro, and fire the action once (on key-down) instead.
                if is_down:
                    self.signals.control_hotkey.emit(action)
                return

        now = time.time()
        if self._last_keyboard_time is not None:
            gap = now - self._last_keyboard_time
            if gap > MIN_RECORDED_GAP:
                self.keyboard_events.append(("sleep", [round(gap, 3)]))
        self._last_keyboard_time = now

        self.keyboard_events.append(("press" if is_down else "release", [code]))

    def _record_mouse_gap(self):
        now = time.time()
        if self._last_mouse_event_time is not None:
            gap = now - self._last_mouse_event_time
            if gap > MIN_RECORDED_GAP:
                self.mouse_events.append(("sleep", [round(gap, 3)]))
        self._last_mouse_event_time = now

    def _on_mouse_event(self, nCode, wParam, mouse_struct):
        if not self.recording:
            return
        if mouse_struct.flags & LLMHF_INJECTED_MASK:
            return  # synthetic input (e.g. another running macro), not the real user
        current_pos = (mouse_struct.pt.x, mouse_struct.pt.y)

        if wParam == WM_LBUTTONDOWN:
            self._record_mouse_gap()
            self.mouse_events.append(("left_down", []))
            self._left_held = True
            return
        if wParam == WM_LBUTTONUP:
            self._record_mouse_gap()
            self.mouse_events.append(("left_up", []))
            self._left_held = False
            return
        if wParam == WM_RBUTTONDOWN:
            self._record_mouse_gap()
            self.mouse_events.append(("right_down", []))
            self._right_held = True
            return
        if wParam == WM_RBUTTONUP:
            self._record_mouse_gap()
            self.mouse_events.append(("right_up", []))
            self._right_held = False
            return

        if wParam == WM_MOUSEMOVE:
            now = time.time()
            if (self._last_mouse_sample_time is not None and
                    now - self._last_mouse_sample_time < MOUSE_SAMPLE_INTERVAL):
                return

            if self._last_mouse_pos is not None:
                dx = current_pos[0] - self._last_mouse_pos[0]
                dy = current_pos[1] - self._last_mouse_pos[1]
                if (dx * dx + dy * dy) ** 0.5 >= MOUSE_MOVE_THRESHOLD:
                    self._record_mouse_gap()
                    # Held-button + hidden cursor is the actual signature of
                    # "game is reading raw relative input for camera
                    # look/aim" - an ordinary held-button drag with the
                    # cursor still visible (e.g. dragging an inventory item)
                    # keeps tracking absolute position normally and must
                    # stay absolute. See MousePathPoint's docstring.
                    if (self._left_held or self._right_held) and not is_cursor_visible():
                        self.mouse_events.append(("move_rel", [dx, dy]))
                    else:
                        self.mouse_events.append(("move", [current_pos[0], current_pos[1]]))
                    self._last_mouse_pos = current_pos
                    self._last_mouse_sample_time = now
            else:
                self._last_mouse_pos = current_pos
                self._last_mouse_sample_time = now

    # -- post-processing: raw events -> Blocks -------------------------------

    def _dedupe_key_repeat(self, events):
        """Drop OS auto-repeat WM_KEYDOWN spam for keys that are already held."""
        held = set()
        result = []
        for name, args in events:
            if name == "press":
                code = args[0]
                if code in held:
                    continue
                held.add(code)
            elif name == "release":
                held.discard(args[0])
            result.append((name, args))
        return result

    def _build_keyboard_blocks(self):
        # Mirrors _build_mouse_blocks: accumulate steps into one block for as
        # long as keyboard activity is continuous, only starting a new block
        # after a real pause (KEYBOARD_BLOCK_SPLIT_GAP). One block per raw
        # key event (the old behavior) turns a few minutes of typing into
        # thousands of top-level blocks - each needing its own real Qt
        # widget with no virtualization, which made long recordings take
        # minutes to render or even reopen. The user still gets normal,
        # per-key-editable content (Split can always break a block back down
        # into individual steps), just grouped into far fewer top-level cards.
        blocks = []
        events = self._dedupe_key_repeat(self.keyboard_events)

        pending_delay = 0.0
        current_steps = None  # list[Step] while a block is open, else None

        def flush():
            nonlocal current_steps
            if current_steps:
                blocks.append(Block.new_block(current_steps))
            current_steps = None

        for name, args in events:
            if name == "sleep":
                pending_delay += args[0]
                if pending_delay >= KEYBOARD_BLOCK_SPLIT_GAP:
                    flush()
                continue

            if current_steps is None:
                current_steps = []
            if pending_delay > MIN_RECORDED_GAP:
                current_steps.append(Step(type="sleep", duration=round(pending_delay, 2)))
            pending_delay = 0.0
            current_steps.append(Step(type=name, key=args[0]))

        flush()
        return blocks

    def _build_mouse_blocks(self):
        blocks = []

        if self.record_mouse and self.start_mouse_pos:
            sx, sy = self.start_mouse_pos
            start_block = Block.new_mouse_path([MousePathPoint(kind="move", x=sx, y=sy)])
            start_block.label = "Return to starting position"
            blocks.append(start_block)

        pending_delay = 0.0
        path_points = None  # list[MousePathPoint] while a path run is open, else None

        def flush_path():
            nonlocal path_points
            if path_points:
                blocks.append(Block.new_mouse_path(path_points))
            path_points = None

        for name, args in self.mouse_events:
            if name == "sleep":
                pending_delay += args[0]
                if pending_delay >= MOUSE_BLOCK_SPLIT_GAP:
                    flush_path()
                continue

            if path_points is None:
                path_points = []

            if name in ("move", "move_rel"):
                x, y = args
                path_points.append(MousePathPoint(kind=name, x=x, y=y, dt=round(pending_delay, 3)))
            else:
                path_points.append(MousePathPoint(kind=name, dt=round(pending_delay, 3)))
            pending_delay = 0.0

        flush_path()
        return blocks
